import {config} from '../config';

export const CONST = {
  loading: 'Loading...',
  RU_LANGS: [
    'ru',
    'az',
    'am',
    'by',
    'ge',
    'kz',
    'kg',
    'md',
    'tj',
    'tm',
    'uz',
    'ua',
  ],
  maxSounds: 10,
  db: {
    sounds: 'DATA_SOUNDS',
    musics: 'DATA_MUSICS',
    notifications: 'Notifications',
    soundCategories: 'SOUNDS_Categories',
    musicCategories: 'MUSICS_Categories',
    users: 'users',
    personalData: 'personalData',
    appData: 'appData',
    favoritesPlay: 'favoritesPlay',
    requests: 'Requests',
  },
  accountStatuses: {
    _free: 'free',
    _premium: 'premium',
  },
  request: {
    to: config.emailForRequests,
    message: {
      subject: 'New request from Meditation Sounds ',
      text: '',
      html: '',
    },
  },
  feedback: {
    maxLengthFirstName: 20,
    maxLengthTopic: 30,
    maxLengthDescription: 500,
    minLengthTopic: 5,
    minLengthDescription: 30,
    intervalSending: 3600,
  },
  language: {
    key: 'language',
    data: [
      {
        id: 1,
        title: 'Русский',
        value: 'RUS',
      },
      {
        id: 2,
        title: 'English',
        value: 'ENG',
      },
    ],
  },
  settings: {
    theme: {
      value: 'MAIN_THEME',
      _key: 'Theme',
    },
    language: {
      value: 'Language',
      _key: 'Language',
    },
    allSizes: {
      value: 'Total',
      _key: 'Total',
    },
    deleteAllFiles: {
      value: 'Delete',
      _key: 'Delete all',
    },
    toSupport: {
      value: 'toSupport',
      _key: 'toSupport',
    },
    termOfService: {
      value: 'TermsOfService',
      _key: 'TermsOfService',
    },
  },
  timer: {
    time1: 600000,
    time2: 1200000,
    time3: 1800000,
    time4: 2700000,
    time5: 3600000,
    time6: 7200000,
    numberColumns: 2,
  },
  THEME: {
    BACKGROUNDCOLOR_LG: ['#3b555d', '#233237', '#204d48', '#233237', '#3b555d'],
    BACKGROUNDCOLOR_LG_Disabled: ['#104E8B', '#4A708B', '#104E8B'],
    BACKGROUNDCOLOR: '#233237',
    BACKGROUNDCOLOR_HEADER: '#3b555d',
    NO_ACTIVE: '#146185',
    TEXT_COLOR: 'white',
    ITEM_COLOR: 'white',
    CHECK_COLOR: '#15a522',
    DANGER_COLOR: '#d81b60',
    name: 'MAIN_THEME',
    TITLE_FONT_SIZE: 22,
  },
  MAIN_BACKGROUNDSTYLES: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  HEADER_OPTIONS: {
    mainBackground: false,
    drawerIcon: 'menu',
    settingsIcon: 'md-settings-sharp',
    notificationsIcon: 'notifications',
    home: 'home',
    back: 'arrow-back-ios',
  },
  PLAYER_OPTIONS: {
    arrowLeft: 'keyboard-arrow-left',
    arrowRight: 'keyboard-arrow-right',
    play: 'play-circle-outline',
    control_play: 'play',
    control_pause: 'pause',
    pause: 'pause-circle-outline',
    library: 'ios-library-sharp',
    checkYes: 'ios-checkmark-sharp',
    heart: 'heart',
    close: 'close',
    edit: 'edit',
    timer: 'timer',
  },
  FLATLIST: {
    numberColumns: 3,
  },
  STORAGE_KEYS: {
    currentPlay: 'currentPlay',
    feedbackInterval: 'feedbackInterval',
    // favoritesPlay: 'favoritesPlay',
  },
  file: 'file://',
};
