import {Asset} from 'expo-asset';

export const dataTab = [
  {
    id: '1',
    title: 'Мои миксы',
  },
  {
    id: '2',
    title: 'Звуки',
  },
  {
    id: '3',
    title: 'Музыка',
  },
  {
    id: '4',
    title: 'Настройки',
  },
];

export const soundCat = [
  {
    id: '1',
    name: 'water',
    img: Asset.fromModule(require('../assets/category/water.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/water_lt.png')).uri,
  },
  {
    id: '2',
    name: 'nature',
    img: Asset.fromModule(require('../assets/category/nature.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/nature_lt.png')).uri,
  },
  {
    id: '3',
    name: 'birds',
    img: Asset.fromModule(require('../assets/category/birds.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/birds_lt.png')).uri,
  },
  {
    id: '4',
    name: 'animals',
    img: Asset.fromModule(require('../assets/category/animals.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/animals_lt.png')).uri,
  },
  {
    id: '5',
    name: 'town',
    img: Asset.fromModule(require('../assets/category/town.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/town_lt.png')).uri,
  },
  {
    id: '6',
    name: 'instruments',
    img: Asset.fromModule(require('../assets/category/instruments.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/instruments_lt.png'))
      .uri,
  },
  {
    id: '7',
    name: 'space',
    img: Asset.fromModule(require('../assets/category/cosmo.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/cosmo_lt.png')).uri,
  },
];

export const musicCat = [
  {
    id: '1',
    name: 'music',
    img: Asset.fromModule(require('../assets/category/music.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/music_lt.png')).uri,
  },
  {
    id: '2',
    name: 'meditations',
    img: Asset.fromModule(require('../assets/category/meditate.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/meditate_lt.png')).uri,
  },
  {
    id: '3',
    name: 'matrices',
    img: Asset.fromModule(require('../assets/category/matrix.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/matrix_lt.png')).uri,
  },
  {
    id: '4',
    name: 'rhythms',
    img: Asset.fromModule(require('../assets/category/soundwave.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/soundwave_lt.png'))
      .uri,
  },
  {
    id: '5',
    name: 'fairytales',
    img: Asset.fromModule(require('../assets/category/fairyTales.png')).uri,
    img_lt: Asset.fromModule(require('../assets/category/fairyTales_lt.png'))
      .uri,
  },
];

export const favoritesCat = {
  MAIN_THEME: [
    require('../assets/category/favoritesMixes.png'),
    require('../assets/category/favoritesBookedSounds.png'),
    require('../assets/category/favoritesBookedMusics.png'),
  ],
  LIGHT_THEME: [
    require('../assets/category/favoritesMixes_lt.png'),
    require('../assets/category/favoritesBookedSounds_lt.png'),
    require('../assets/category/favoritesBookedMusics_lt.png'),
  ],
};

export const favoritesIcon = {
  MAIN_THEME: {
    toFavoritesScreen: require('../assets/toFavoritesScreen.png'),
  },
  LIGHT_THEME: {
    toFavoritesScreen: require('../assets/toFavoritesScreen_lt.png'),
  },
};

export const icons = {
  eqGif: require('../assets/eq.gif'),
  eqPng: require('../assets/eq.png'),
};

export const mixData = {
  img: require('../assets/img/mix.png'),
};

export const DATA_SOUNDS = [
  {
    id: '1',
    name: 'river',
    img: Asset.fromModule(require('../assets/img/river.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Water/River.aac')).uri,
  },
  {
    id: '2',
    name: 'Wellspring',
    img: Asset.fromModule(require('../assets/img/Wellspring.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Water/Wellspring.aac'))
      .uri,
  },
  {
    id: '3',
    name: 'MountainStream',
    img: Asset.fromModule(require('../assets/img/MountainStream.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(
      require('../assets/sounds/Water/MountainStream.aac'),
    ).uri,
  },
  {
    id: '4',
    name: 'ocean',
    img: Asset.fromModule(require('../assets/img/ocean.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Water/Ocean.aac')).uri,
  },
  {
    id: '5',
    name: 'calmlWave',
    img: Asset.fromModule(require('../assets/img/calmlWave.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Water/CalmWaves.aac'))
      .uri,
  },
  {
    id: '6',
    name: 'Waves',
    img: Asset.fromModule(require('../assets/img/Waves.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '7',
    name: 'Tsunami',
    img: Asset.fromModule(require('../assets/img/Tsunami.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '8',
    name: 'lake',
    img: Asset.fromModule(require('../assets/img/lake.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '9',
    name: 'LakeBaikal',
    img: Asset.fromModule(require('../assets/img/LakeBaikal.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '10',
    name: 'waterfall',
    img: Asset.fromModule(require('../assets/img/waterfall.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '11',
    name: 'SeaAndSeagulls',
    img: Asset.fromModule(require('../assets/img/SeaAndSeagulls.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '12',
    name: 'SeaAndDolphins',
    img: Asset.fromModule(require('../assets/img/SeaAndDolphins.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '13',
    name: 'underWater',
    img: Asset.fromModule(require('../assets/img/underWater.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '14',
    name: 'HydrothermalVents',
    img: Asset.fromModule(require('../assets/img/HydrothermalVents.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '15',
    name: 'diving',
    img: Asset.fromModule(require('../assets/img/diving.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '16',
    name: 'waterSplashing',
    img: Asset.fromModule(require('../assets/img/waterSplashing.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '17',
    name: 'SpringDawn',
    img: Asset.fromModule(require('../assets/img/SpringDawn.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Nature/SpringDawn.aac'))
      .uri,
  },
  {
    id: '18',
    name: 'Spring',
    img: Asset.fromModule(require('../assets/img/Spring.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Nature/Spring.aac')).uri,
  },
  {
    id: '19',
    name: 'rain',
    img: Asset.fromModule(require('../assets/img/rain.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Nature/Rain.aac')).uri,
  },
  {
    id: '20',
    name: 'urbanRain',
    img: Asset.fromModule(require('../assets/img/urbanRain.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '21',
    name: 'rainInTheRoof',
    img: Asset.fromModule(require('../assets/img/rainInTheRoof.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '22',
    name: 'Rainfall',
    img: Asset.fromModule(require('../assets/img/Rainfall.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '23',
    name: 'RainWithThunderstorm',
    img: Asset.fromModule(require('../assets/img/RainWithThunderstorm.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '24',
    name: 'ThunderFromLightning',
    img: Asset.fromModule(require('../assets/img/ThunderFromLightning.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '25',
    name: 'thunder',
    img: Asset.fromModule(require('../assets/img/thunder.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '26',
    name: 'cave',
    img: Asset.fromModule(require('../assets/img/cave.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '27',
    name: 'winds',
    img: Asset.fromModule(require('../assets/img/winds.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '28',
    name: 'windThroughTheTrees',
    img: Asset.fromModule(require('../assets/img/windThroughTheTrees.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '29',
    name: 'windsGusts',
    img: Asset.fromModule(require('../assets/img/windsGusts.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '30',
    name: 'Hurricane',
    img: Asset.fromModule(require('../assets/img/Hurricane.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '31',
    name: 'HurricaneWindOutsideTheWindow',
    img: Asset.fromModule(
      require('../assets/img/HurricaneWindOutsideTheWindow.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '32',
    name: 'Blizzard',
    img: Asset.fromModule(require('../assets/img/Blizzard.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '33',
    name: 'Hail',
    img: Asset.fromModule(require('../assets/img/Hail.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '34',
    name: 'rustleOfLeaves',
    img: Asset.fromModule(require('../assets/img/rustleOfLeaves.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '35',
    name: 'night',
    img: Asset.fromModule(require('../assets/img/night.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '36',
    name: 'NightInTheField',
    img: Asset.fromModule(require('../assets/img/NightInTheField.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '37',
    name: 'EveningInTheVillage',
    img: Asset.fromModule(require('../assets/img/EveningInTheVillage.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '38',
    name: 'SummerField',
    img: Asset.fromModule(require('../assets/img/SummerField.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '39',
    name: 'campfire',
    img: Asset.fromModule(require('../assets/img/fire.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '40',
    name: 'forest',
    img: Asset.fromModule(require('../assets/img/forest.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '41',
    name: 'forestSunset',
    img: Asset.fromModule(require('../assets/img/forestSunset.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '42',
    name: 'canadianForest',
    img: Asset.fromModule(require('../assets/img/canadianForest.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '43',
    name: 'walkingInTheWoods',
    img: Asset.fromModule(require('../assets/img/walkingInTheWoods.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '44',
    name: 'tuscany',
    img: Asset.fromModule(require('../assets/img/tuscany.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '45',
    name: 'iceSnow',
    img: Asset.fromModule(require('../assets/img/iceSnow.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '46',
    name: 'ArcticCold',
    img: Asset.fromModule(require('../assets/img/ArcticCold.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '47',
    name: 'BreakingIce',
    img: Asset.fromModule(require('../assets/img/BreakingIce.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '48',
    name: 'Lava',
    img: Asset.fromModule(require('../assets/img/Lava.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '49',
    name: 'Farm',
    img: Asset.fromModule(require('../assets/img/Farm.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '50',
    name: 'birdSongs',
    img: Asset.fromModule(require('../assets/img/birdSongs.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Birds/BirdSong.aac')).uri,
  },
  {
    id: '51',
    name: 'MorningBirds',
    img: Asset.fromModule(require('../assets/img/MorningBirds.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Birds/MorningBirds.aac'))
      .uri,
  },
  {
    id: '52',
    name: 'Woodthrush',
    img: Asset.fromModule(require('../assets/img/Woodthrush.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Birds/Woodthrush.aac'))
      .uri,
  },
  {
    id: '53',
    name: 'Nightingale',
    img: Asset.fromModule(require('../assets/img/Nightingale.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '54',
    name: 'NightingaleNearTheStream',
    img: Asset.fromModule(require('../assets/img/NightingaleNearTheStream.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '55',
    name: 'OrientalNightingale',
    img: Asset.fromModule(require('../assets/img/OrientalNightingale.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '56',
    name: 'Goldfinch',
    img: Asset.fromModule(require('../assets/img/Goldfinch.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '57',
    name: 'Starlings',
    img: Asset.fromModule(require('../assets/img/Starlings.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '58',
    name: 'Swallows',
    img: Asset.fromModule(require('../assets/img/Swallows.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '59',
    name: 'Crane',
    img: Asset.fromModule(require('../assets/img/Crane.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '60',
    name: 'Bullfinch',
    img: Asset.fromModule(require('../assets/img/Bullfinch.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '61',
    name: 'loon',
    img: Asset.fromModule(require('../assets/img/loon.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '62',
    name: 'Cuckoo',
    img: Asset.fromModule(require('../assets/img/Cuckoo.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '63',
    name: 'Owl',
    img: Asset.fromModule(require('../assets/img/Owl.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '64',
    name: 'Woodpecker',
    img: Asset.fromModule(require('../assets/img/Woodpecker.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '65',
    name: 'Pigeon',
    img: Asset.fromModule(require('../assets/img/Pigeon.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '66',
    name: 'Goose',
    img: Asset.fromModule(require('../assets/img/Goose.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '67',
    name: 'Cock',
    img: Asset.fromModule(require('../assets/img/Cock.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '68',
    name: 'Chicken',
    img: Asset.fromModule(require('../assets/img/Chicken.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '69',
    name: 'DogWhining',
    img: Asset.fromModule(require('../assets/img/DogWhining.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Animals/DogWhining.aac'))
      .uri,
  },
  {
    id: '70',
    name: 'catPurring',
    img: Asset.fromModule(require('../assets/img/catPurring.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Animals/CatPurring.aac'))
      .uri,
  },
  {
    id: '71',
    name: 'Tiger',
    img: Asset.fromModule(require('../assets/img/Tiger.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Animals/Tiger.aac')).uri,
  },
  {
    id: '72',
    name: 'Jaguar',
    img: Asset.fromModule(require('../assets/img/Jaguar.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '73',
    name: 'Leopard',
    img: Asset.fromModule(require('../assets/img/Leopard.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '74',
    name: 'Sheepdog',
    img: Asset.fromModule(require('../assets/img/Sheepdog.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '75',
    name: 'Spitz',
    img: Asset.fromModule(require('../assets/img/Spitz.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '76',
    name: 'Horse',
    img: Asset.fromModule(require('../assets/img/Horse.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '77',
    name: 'Bull',
    img: Asset.fromModule(require('../assets/img/Bull.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '78',
    name: 'Cow',
    img: Asset.fromModule(require('../assets/img/Cow.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '79',
    name: 'Pig',
    img: Asset.fromModule(require('../assets/img/Pig.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '80',
    name: 'Hedgehog',
    img: Asset.fromModule(require('../assets/img/Hedgehog.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '81',
    name: 'Squirrel',
    img: Asset.fromModule(require('../assets/img/Squirrel.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '82',
    name: 'Wolf',
    img: Asset.fromModule(require('../assets/img/Wolf.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '83',
    name: 'Bear',
    img: Asset.fromModule(require('../assets/img/Bear.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '84',
    name: 'Chimpanzee',
    img: Asset.fromModule(require('../assets/img/Chimpanzee.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '85',
    name: 'Orangutan',
    img: Asset.fromModule(require('../assets/img/Orangutan.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '86',
    name: 'Hyena',
    img: Asset.fromModule(require('../assets/img/Hyena.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '87',
    name: 'Python',
    img: Asset.fromModule(require('../assets/img/Python.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '88',
    name: 'Dolphins',
    img: Asset.fromModule(require('../assets/img/Dolphins.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '89',
    name: 'SpermWhale',
    img: Asset.fromModule(require('../assets/img/SpermWhale.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '90',
    name: 'frogs',
    img: Asset.fromModule(require('../assets/img/frogs.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '91',
    name: 'town',
    img: Asset.fromModule(require('../assets/img/town.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Town/Town.aac')).uri,
  },
  {
    id: '92',
    name: 'Track',
    img: Asset.fromModule(require('../assets/img/Track.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Town/Track.aac')).uri,
  },
  {
    id: '93',
    name: 'Highway',
    img: Asset.fromModule(require('../assets/img/Highway.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Town/Highway.aac')).uri,
  },
  {
    id: '94',
    name: 'TrafficJam',
    img: Asset.fromModule(require('../assets/img/TrafficJam.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '95',
    name: 'Tunnel',
    img: Asset.fromModule(require('../assets/img/Tunnel.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '96',
    name: 'Train',
    img: Asset.fromModule(require('../assets/img/Train.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '97',
    name: 'trainInTheDistance',
    img: Asset.fromModule(require('../assets/img/trainInTheDistance.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '98',
    name: 'Airplane',
    img: Asset.fromModule(require('../assets/img/Airplane.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '99',
    name: 'AircraftEngine',
    img: Asset.fromModule(require('../assets/img/AircraftEngine.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '100',
    name: 'Tractor',
    img: Asset.fromModule(require('../assets/img/Tractor.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '101',
    name: 'crowd',
    img: Asset.fromModule(require('../assets/img/crowd.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '102',
    name: 'NightСlub',
    img: Asset.fromModule(require('../assets/img/NightСlub.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '103',
    name: 'EmptyStreet',
    img: Asset.fromModule(require('../assets/img/EmptyStreet.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '104',
    name: 'ChurchBell',
    img: Asset.fromModule(require('../assets/img/ChurchBell.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '105',
    name: 'vacuum',
    img: Asset.fromModule(require('../assets/img/vacuum.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '106',
    name: 'floorClock',
    img: Asset.fromModule(require('../assets/img/floorClock.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '107',
    name: 'flute',
    img: Asset.fromModule(require('../assets/img/flute.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Instruments/Flute.aac'))
      .uri,
  },
  {
    id: '108',
    name: 'DoubleBass',
    img: Asset.fromModule(require('../assets/img/DoubleBass.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(
      require('../assets/sounds/Instruments/DoubleBass.aac'),
    ).uri,
  },
  {
    id: '109',
    name: 'Djembe',
    img: Asset.fromModule(require('../assets/img/Djembe.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/sounds/Instruments/Djembe.aac'))
      .uri,
  },
  {
    id: '110',
    name: 'Flute2',
    img: Asset.fromModule(require('../assets/img/Flute2.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '111',
    name: 'duduk',
    img: Asset.fromModule(require('../assets/img/duduk.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '112',
    name: 'Horn',
    img: Asset.fromModule(require('../assets/img/Horn.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '113',
    name: 'piano',
    img: Asset.fromModule(require('../assets/img/piano.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '114',
    name: 'Harp',
    img: Asset.fromModule(require('../assets/img/Harp.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '115',
    name: 'Ukulele',
    img: Asset.fromModule(require('../assets/img/Ukulele.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '116',
    name: 'Djembe2',
    img: Asset.fromModule(require('../assets/img/Djembe2.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '117',
    name: 'Djembe3',
    img: Asset.fromModule(require('../assets/img/Djembe3.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '118',
    name: 'Earth',
    img: Asset.fromModule(require('../assets/img/Earth.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '119',
    name: 'Mars',
    img: Asset.fromModule(require('../assets/img/Mars.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '120',
    name: 'jupiter',
    img: Asset.fromModule(require('../assets/img/jupiter.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '121',
    name: 'Saturn',
    img: Asset.fromModule(require('../assets/img/Saturn.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '122',
    name: 'BlackHole',
    img: Asset.fromModule(require('../assets/img/BlackHole.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
];

export const DATA_MUSIC = [
  {
    id: '1',
    name: 'musicBox',
    img: Asset.fromModule(require('../assets/img/musicBox.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/musics/Music/MusicBox.aac')).uri,
  },
  {
    id: '2',
    name: 'infinity',
    img: Asset.fromModule(require('../assets/img/infinity.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/musics/Music/Infinity.aac')).uri,
  },
  {
    id: '3',
    name: 'orchestral',
    img: Asset.fromModule(require('../assets/img/orchestral.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/musics/Music/Orchestral.aac'))
      .uri,
  },
  {
    id: '4',
    name: 'lounge',
    img: Asset.fromModule(require('../assets/img/lounge.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '5',
    name: 'windChimes',
    img: Asset.fromModule(require('../assets/img/windChimes.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '6',
    name: 'lullaby',
    img: Asset.fromModule(require('../assets/img/lullaby.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '7',
    name: 'lullabyBrums',
    img: Asset.fromModule(require('../assets/img/lullabyBrums.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '8',
    name: 'ShamanicDrum',
    img: Asset.fromModule(require('../assets/img/ShamanicDrum.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '9',
    name: 'HarpMusic',
    img: Asset.fromModule(require('../assets/img/HarpMusic.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '10',
    name: 'Balalaika',
    img: Asset.fromModule(require('../assets/img/Balalaika.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '11',
    name: 'Basetlya',
    img: Asset.fromModule(require('../assets/img/Basetlya.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '12',
    name: 'UkuleleMusic',
    img: Asset.fromModule(require('../assets/img/UkuleleMusic.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '13',
    name: 'GuitarMusic',
    img: Asset.fromModule(require('../assets/img/GuitarMusic.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '14',
    name: 'Pianoforte',
    img: Asset.fromModule(require('../assets/img/Pianoforte.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '15',
    name: 'Piano2',
    img: Asset.fromModule(require('../assets/img/Piano2.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '16',
    name: '10Hz',
    img: Asset.fromModule(require('../assets/img/10Hz.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/musics/Rhytms/BrainScanner.aac'))
      .uri,
  },
  {
    id: '17',
    name: 'BR_forSleep',
    img: Asset.fromModule(require('../assets/img/BR_forSleep.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(require('../assets/musics/Rhytms/BR_forSleep.aac'))
      .uri,
  },
  {
    id: '18',
    name: 'BR_forLucidDreaming',
    img: Asset.fromModule(require('../assets/img/BR_forLucidDreaming.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(
      require('../assets/musics/Rhytms/BR_forLucidDreaming.aac'),
    ).uri,
  },
  {
    id: '19',
    name: 'BR_forRecovery',
    img: Asset.fromModule(require('../assets/img/BR_forRecovery.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '20',
    name: 'BR_ofLoveAndHarmony',
    img: Asset.fromModule(require('../assets/img/BR_ofLoveAndHarmony.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '21',
    name: 'BR_thirdEye',
    img: Asset.fromModule(require('../assets/img/BR_thirdEye.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '22',
    name: 'BR_forAttractingMoneyAndSuccess',
    img: Asset.fromModule(
      require('../assets/img/BR_forAttractingMoneyAndSuccess.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '23',
    name: 'BR_forBrainActivity',
    img: Asset.fromModule(require('../assets/img/BR_forBrainActivity.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '24',
    name: 'BR_forTheTreatmentOfNerves',
    img: Asset.fromModule(
      require('../assets/img/BR_forTheTreatmentOfNerves.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '25',
    name: 'BR_fromHeadaches',
    img: Asset.fromModule(require('../assets/img/BR_fromHeadaches.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '26',
    name: 'BR_toCombatChronicFatigue',
    img: Asset.fromModule(
      require('../assets/img/BR_toCombatChronicFatigue.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '27',
    name: 'BR_forOvercomingAddiction',
    img: Asset.fromModule(
      require('../assets/img/BR_forOvercomingAddiction.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '28',
    name: 'BR_forTheTreatmentOfHangover',
    img: Asset.fromModule(
      require('../assets/img/BR_forTheTreatmentOfHangover.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '29',
    name: 'BR_forWeightLoss',
    img: Asset.fromModule(require('../assets/img/BR_forWeightLoss.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '30',
    name: 'BR_forAllergyTreatment',
    img: Asset.fromModule(require('../assets/img/BR_forAllergyTreatment.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '31',
    name: 'BR_forHairGrowth',
    img: Asset.fromModule(require('../assets/img/BR_forHairGrowth.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '32',
    name: 'RejuvenationOfTheBody',
    img: Asset.fromModule(require('../assets/img/RejuvenationOfTheBody.png'))
      .uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(
      require('../assets/musics/Meditations/RejuvenationOfTheBody.aac'),
    ).uri,
  },
  {
    id: '33',
    name: 'MatrixForHealthyAndSoundSleep',
    img: Asset.fromModule(
      require('../assets/img/MatrixForHealthyAndSoundSleep.png'),
    ).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(
      require('../assets/musics/Matrices/MatrixForHealthyAndSoundSleep.aac'),
    ).uri,
  },
  {
    id: '34',
    name: 'TheTaleofTsarSaltan',
    img: Asset.fromModule(require('../assets/img/TheTaleofTsarSaltan.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: Asset.fromModule(
      require('../assets/musics/FairyTales/TheTaleofTsarSaltan.aac'),
    ).uri,
  },
  {
    id: '35',
    name: 'ForMoney',
    img: Asset.fromModule(require('../assets/img/ForMoney.png')).uri,
    location: 'app',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '36',
    name: 'DeepSleep',
    img: Asset.fromModule(require('../assets/img/DeepSleep.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '37',
    name: 'CalmingTheNerves',
    img: Asset.fromModule(require('../assets/img/CalmingTheNerves.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '38',
    name: 'Loneliness',
    img: Asset.fromModule(require('../assets/img/Loneliness.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '39',
    name: 'DevelopmentOfIntuition',
    img: Asset.fromModule(require('../assets/img/DevelopmentOfIntuition.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '40',
    name: 'HearingRestoration',
    img: Asset.fromModule(require('../assets/img/HearingRestoration.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '41',
    name: 'GKT',
    img: Asset.fromModule(require('../assets/img/GKTtrack.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '42',
    name: 'CompleteHealingDuringSleep',
    img: Asset.fromModule(
      require('../assets/img/CompleteHealingDuringSleep.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '43',
    name: 'DecreasedAppetite',
    img: Asset.fromModule(require('../assets/img/DecreasedAppetite.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '44',
    name: "Women'sHealth",
    img: Asset.fromModule(require("../assets/img/Women'sHealth.png")).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '45',
    name: 'ActivationOfTheMemoryAndThinkingCenter',
    img: Asset.fromModule(
      require('../assets/img/ActivationOfTheMemoryAndThinkingCenter.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '46',
    name: 'MatrixForReassurance',
    img: Asset.fromModule(require('../assets/img/MatrixForReassurance.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '47',
    name: 'MatrixForRecoveryAfter40_50Years',
    img: Asset.fromModule(
      require('../assets/img/MatrixForRecoveryAfter40_50Years.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '48',
    name: 'MatrixForSleepAndRest',
    img: Asset.fromModule(require('../assets/img/MatrixForSleepAndRest.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '49',
    name: 'MatrixOfDepression',
    img: Asset.fromModule(require('../assets/img/MatrixOfDepression.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '50',
    name: 'MatrixYinYang',
    img: Asset.fromModule(require('../assets/img/MatrixYinYang.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '51',
    name: 'MatrixForRestorationOfVision',
    img: Asset.fromModule(
      require('../assets/img/MatrixForRestorationOfVision.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '52',
    name: 'MatrixForGastrointestinalHealing',
    img: Asset.fromModule(
      require('../assets/img/MatrixForGastrointestinalHealing.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '53',
    name: 'IvanTsarevichAndTheGreyWolf',
    img: Asset.fromModule(require('../assets/img/PrinceIvanAndTheGreyWolf.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '54',
    name: 'RedHat',
    img: Asset.fromModule(require('../assets/img/RedHat.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '55',
    name: 'TheTaleOfTheDeadPrincessAndTheSevenHeroes',
    img: Asset.fromModule(
      require('../assets/img/TheTaleOfTheDeadPrincessAndTheSevenHeroes.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '56',
    name: 'ScarletFlower',
    img: Asset.fromModule(require('../assets/img/ScarletFlower.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '57',
    name: 'TheTaleOfTheFishermanAndTheFish',
    img: Asset.fromModule(
      require('../assets/img/TheTaleOfTheFishermanAndTheFish.png'),
    ).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '58',
    name: 'Cinderella',
    img: Asset.fromModule(require('../assets/img/Cinderella.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '59',
    name: 'ThreeLittlePigs',
    img: Asset.fromModule(require('../assets/img/ThreeBeggars.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '60',
    name: 'PussInBoots',
    img: Asset.fromModule(require('../assets/img/PussInBoots.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '61',
    name: 'Teremok',
    img: Asset.fromModule(require('../assets/img/Teremok.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '62',
    name: 'Kolobok',
    img: Asset.fromModule(require('../assets/img/Kolobok.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '63',
    name: 'TheLukomoryeOakIsGreen',
    img: Asset.fromModule(require('../assets/img/LukomoryeHasAGreenOak.png'))
      .uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '64',
    name: 'Thumbelina',
    img: Asset.fromModule(require('../assets/img/Thumbelina.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '65',
    name: 'TsvetikSemitsvetik',
    img: Asset.fromModule(require('../assets/img/TsvetikSemitsvetik.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '66',
    name: 'DrAibolit',
    img: Asset.fromModule(require('../assets/img/DoctorAibolit.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
  {
    id: '67',
    name: 'Moidodyr',
    img: Asset.fromModule(require('../assets/img/Moidodyr.png')).uri,
    location: 'cloud',
    booked: false,
    new: false,
    sound: '',
  },
];
