import {CONST} from './const';

export const LANGUAGE = {
  RUS: {
    name: 'RUS',
    currentMix: 'Текущий микс',
    categorySounds: {},
    categoryMusics: {},
    categoryFavorites: [
      {
        id: 1,
        name: 'Мои Миксы',
        category: 'mixes',
      },
      {
        id: 2,
        name: 'Звуки',
        category: 'bookedSounds',
      },
      {
        id: 3,
        name: 'Музыка',
        category: 'bookedMusics',
      },
    ],
    section: {
      favoriteMix: 'Избранное',
      sounds: 'Звуки',
      musics: 'Музыка',
      settings: 'Настройки',
    },
    headerTitle: {
      sounds: 'Библиотека звуков',
      musics: 'Библиотека музыки',
      myMixes: 'Библиотека моих миксов',
      meditatons: 'Библиотека медитаций',
      player: 'Плеер',
      settings: 'Настройки',
      feedback: 'Поддержка',
      language: 'Смена языка',
      notifications: 'Уведомления',
      library: 'Библиотека',
      brainWaves: 'Бинауральные ритмы',
      music: 'Музыка',
      sound: 'Звуки',
      timer: 'Таймер',
      login: 'Вход в систему',
      resetPassword: 'Сброс пароля',
      signUp: 'Регистрация',
    },
    buttons: {
      add: 'Добавить',
      clear: 'Очистить',
      signIn: 'Войти',
      signUp: 'Регистрация',
      resetPassword: 'Сброс пароля',
    },
    loading: 'Загрузка...',
    newSound: 'NEW',
    notifications: {
      noNotifications: 'У вас пока нет уведомлений.',
      title: 'Добавлен новый звук.',
      commentBR: 'В коллекцию "Мозговые волны" добавлен новый звук: ',
      commentMusic: 'В коллекцию "Музыка" добавлен новый звук: ',
      commentSounds: 'В коллекцию "Звуки" добавлен новый звук: ',
    },
    settings: {
      titleDecoration: 'Оформление',
      nameTheme: 'Светлая тема',
      nameLanguage: 'Сменить язык',
      titleService: 'Служебные',
      nameAllSizesFile: 'Общий размер скачанных звуков',
      nameDeleteAllFiles: 'Удалить все скачанные файлы',
      nameToSupport: 'Написать в поддержку',
      titleInformation: 'Информация',
      nameTermsOfService: 'Условия обслуживания',
    },
    timer: {
      mins: 'минут',
      hour: 'час',
      hours: 'часа',
      individual: 'Индивидуальный',
      stopTimerTitle: 'Остановить',
      timerExitApp: 'Закрыть приложение по окончанию таймера',
      buttonNo: 'Отмена',
      buttonYes: 'OK',
    },
    Messages: {
      emptyList: 'У Вас нет ничего в этом миксе',
      emptyBookedList: 'Вы пока ничего не добавили в избранное',
      emptyOwnMixes: 'У Вас пока нет своих своих миксов',
      element: 'Элементов',
      currentMix: 'Текущий микс',
      fileNotFound: 'Файл отсутствует на устройстве!',
      switchToCloud:
        'Проигрывание возможно через интернет после повторной попытки.',
      noAccount: 'У вас нет учетной записи?',
      hasAccount: 'У вас уже есть учетная запись?',
      forgotPassword: 'Забыли пароль?',
    },
    modalMessages: {
      clearSoundList: {
        typeMessage: 'ClearSoundList',
        show: true,
        title: 'Внимание',
        message: 'Вы действительно хотите полностью очистить список плэйлиста?',
        buttonCancel: 'Нет',
        buttonYes: 'Да',
      },
      addFavoriteMix: {
        typeMessage: 'AddFavoriteMix',
        category: '',
        show: true,
        title: 'Сохранение микса',
        message: 'Введите название',
        buttonCancel: 'Отмена',
        buttonYes: 'Сохранить',
      },
      editFavoriteMix: {
        typeMessage: 'EditFavoriteMix',
        show: true,
        title: 'Изменение названия микса',
        message: 'Введите новое название',
        buttonCancel: 'Отмена',
        buttonYes: 'Сохранить',
      },
      removeFavoriteMix: {
        typeMessage: 'RemoveFavoriteMix',
        show: true,
        title: 'Внимание',
        message: 'Вы действительно хотите удалить микс',
        buttonCancel: 'Отмена',
        buttonYes: 'Удалить',
      },
      removeFavoriteAllMix: {
        typeMessage: 'removeFavoriteAllMix',
        show: true,
        title: 'Внимание',
        message: 'Вы действительно хотите очистить весь список миксов?',
        buttonCancel: 'Отмена',
        buttonYes: 'Удалить',
      },
      sameNameFound: {
        typeMessage: 'sameNameFound',
        show: true,
        title: 'Внимание',
        message:
          'Такое название уже использовано! Попробуйте придумать другое название для своего микса.',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      emptyName: {
        typeMessage: 'emptyName',
        show: true,
        title: 'Внимание',
        message: 'Название не может быть пустым.',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      sameMixFound: {
        typeMessage: 'sameMixFound',
        show: true,
        title: 'Внимание',
        message1:
          'Такой микс уже существует в списке моих миксов под названием: ',
        message: '',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      exitApp: {
        typeMessage: 'exitApp',
        show: true,
        title: 'Внимание',
        message: 'Вы действительно хотите выйте из приложения?',
        buttonCancel: 'Нет',
        buttonYes: 'Да',
      },
      OpenDescription: {
        typeMessage: 'OpenDescription',
        show: true,
        title: 'Описание ритма',
        message: '',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      downloadFromCloud: {
        typeMessage: 'downloadFromCloud',
        show: true,
        title: 'Скачивание файла',
        message: '',
        message1: 'Вы действительно хотите скачать файл',
        message2:
          'на своё устройство, чтобы иметь возможность прослушивать его без подключения к интернету?',
        size: 'Размер файла:',
        storage: '',
        name: '',
        category: '',
        id: '',
        buttonCancel: 'Нет',
        buttonYes: 'Да',
      },
      endDownload: {
        typeMessage: 'endDownload',
        show: true,
        title: 'Загрузка',
        message: 'Загрузка завершена успешно!',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      deleteFromDevice: {
        typeMessage: 'deleteFromDevice',
        show: true,
        title: 'Удаление файла',
        message: '',
        message1: 'Вы действительно хотите удалить файл',
        message2:
          'с устройства? У вас останется возможность прослушивать этот файл через интернет.',
        sound: '',
        id: '',
        name: '',
        size: 'Размер файла:',
        category: '',
        buttonCancel: 'Нет',
        buttonYes: 'Да',
      },
      deleteAllFromDevice: {
        typeMessage: 'deleteAllFromDevice',
        show: true,
        title: 'Удаление всех скачанных файлов',
        message:
          'Вы действительно хотите удалить все скачанные звуки с устройства? У вас останется возможность прослушивать через интернет или скачать необходимые звуки на телефон заново.',
        buttonCancel: 'Нет',
        buttonYes: 'Да',
      },
      endDelete: {
        typeMessage: 'endDownload',
        show: true,
        title: 'Удаление',
        message: 'Файл удален!',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      endDeleteAll: {
        typeMessage: 'endDeleteAll',
        show: true,
        title: 'Удаление всех скачанных звуков',
        message: '',
        message2: 'Все скачанные звуки удалены! Всего - ',
        message3: '. Общий объем: ',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      noFilesToDelete: {
        typeMessage: 'noFilesToDelete',
        show: true,
        title: 'Удаление всех скачанных звуков',
        message: 'Нет файлов на удаление!',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      TotalSize: {
        typeMessage: 'TotalSize',
        show: true,
        title: 'Размер скачанных файлов',
        message: '',
        message1: 'Всего в каталоге "Звуки":     ',
        message2: 'Всего в каталоге "Музыка":   ',
        message3: 'Всего в каталоге "Волны":     ',
        message4: 'Всего во всех каталогах:     ',
        buttonCancel: '',
        buttonYes: 'Ok',
      },
      feedbackSuccess: {
        typeMessage: 'feedbackSuccess',
        show: true,
        title: 'Обращение принято',
        message: '',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      maxSounds: {
        typeMessage: 'maxSounds',
        show: true,
        title: 'Превышен лимит',
        message: `Вы можете добавить не более ${CONST.maxSounds} звуков!`,
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      error: {
        typeMessage: 'error',
        show: true,
        title: 'Ошибка!',
        message: '',
        buttonCancel: '',
        buttonYes: 'ОК',
      },
    },
    feedback: {
      firstName: 'Ваше имя',
      emailLabel: 'Email',
      topicLabel: 'Тема',
      descriptionLabel: 'Описание вашего обращения',
      button: 'Отправить',
      errors: {
        intervalSending: 'Отправка следующего обращения будет возможно через ',
        incorrectEmail: 'Введен некорректный email!',
        emptyName: 'Введите ваше имя',
        emptyTopic: 'Введите тему обращения',
        emptyDescription: 'Опишите ваше обращение',
        maxLengthName: `Имя не должно превышать ${CONST.feedback.maxLengthFirstName} знаков`,
        maxLengthTopic: `Название темы не должно превышать ${CONST.feedback.maxLengthTopic} знаков`,
        maxLengthDescription: `Описание обращения не должно превышать ${CONST.feedback.maxLengthDescription} знаков`,
        minLengthTopic: `Название темы не должно быть меньше ${CONST.feedback.minLengthTopic} знаков`,
        minLengthDescription: `Описание обращения не должно быть меньше ${CONST.feedback.minLengthDescription} знаков`,
      },
      resultSuccess: 'Обращение принято под номером MS ',
      resultError: 'Ошибка отправки обращения ',
    },
  },
  ENG: {
    name: 'ENG',
    currentMix: 'Current Mix',
    categorySounds: {},
    categoryMusics: {},
    categoryFavorites: [
      {
        id: 1,
        name: 'My Mixes',
        category: 'mixes',
      },
      {
        id: 2,
        name: 'Sounds',
        category: 'bookedSounds',
      },
      {
        id: 3,
        name: 'Musics',
        category: 'bookedMusics',
      },
    ],
    section: {
      favoriteMix: 'Favourites',
      sounds: 'Sounds',
      musics: 'Musics',
      settings: 'Settings',
    },
    headerTitle: {
      sounds: 'Sound Library',
      musics: 'Music Library',
      myMixes: 'My Mixes Library',
      meditatons: 'Meditation Library',
      player: 'Player',
      settings: 'Settings',
      feedback: 'Support',
      language: 'Language change',
      notifications: 'Notifications',
      library: 'Library',
      brainWaves: 'Binaural rhythms',
      music: 'Music',
      sound: 'Sounds',
      timer: 'Timer',
      login: 'Login',
      resetPassword: 'Reset Password',
      signUp: 'Registration',
    },
    buttons: {
      add: 'Add',
      clear: 'Clear',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      resetPassword: 'Reset Password',
    },
    loading: 'Loading...',
    newSound: 'NEW',
    notifications: {
      noNotifications: "You don't have any notifications yet.",
      title: 'Added a new sound.',
      commentBR: 'A new sound has been added to the "Brain Waves" collection: ',
      commentMusic: 'A new sound has been added to the "Music" collection: ',
      commentSounds: 'A new sound has been added to the "Sounds" collection: ',
    },
    settings: {
      titleDecoration: 'Decoration',
      nameTheme: 'Light theme',
      nameLanguage: 'Change the language',
      titleServices: 'Services',
      nameAllSizesFile: 'Total size of downloaded sounds',
      nameDeleteAllFiles: 'Delete all downloaded files',
      nameToSupport: 'Write to support',
      titleInformation: 'Information',
      nameTermsOfService: 'Terms of service',
    },
    timer: {
      mins: 'minutes',
      hour: 'hour',
      hours: 'hours',
      individual: 'Individual',
      stopTimerTitle: 'Stop',
      timerExitApp: 'Close the application at the end of the timer',
      buttonNo: 'Cancel',
      buttonYes: 'OK',
    },
    Messages: {
      emptyList: "You don't have anything in this mixе",
      emptyBookedList: "You haven't added anything to your favorites yet",
      emptyOwnMixes: "You don't have your own mixes yet",
      element: 'Elements',
      currentMix: 'Current Mix',
      fileNotFound: 'The file is missing on the device!',
      switchToCloud:
        'Playback is possible via the Internet after a second attempt.',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      forgotPassword: 'Forgot Password?',
    },
    modalMessages: {
      clearSoundList: {
        typeMessage: 'ClearSoundList',
        show: true,
        title: 'Attention',
        message: 'Do you really want to completely clear the playlist list?',
        buttonCancel: 'No',
        buttonYes: 'Yes',
      },
      addFavoriteMix: {
        typeMessage: 'AddFavoriteMix',
        category: '',
        show: true,
        title: 'Saving the mix',
        message: 'Enter a name',
        buttonCancel: 'Cancel',
        buttonYes: 'Save',
      },
      editFavoriteMix: {
        typeMessage: 'EditFavoriteMix',
        show: true,
        title: 'Changing the name of the mix',
        message: 'Enter a name',
        buttonCancel: 'Cancel',
        buttonYes: 'Save',
      },
      removeFavoriteMix: {
        typeMessage: 'RemoveFavoriteMix',
        show: true,
        title: 'Attention',
        message: 'Do you really want to delete the mix',
        buttonCancel: 'Cancel',
        buttonYes: 'Remove',
      },
      removeFavoriteAllMix: {
        typeMessage: 'removeFavoriteAllMix',
        show: true,
        title: 'Attention',
        message: 'Do you really want to clear the entire mix list?',
        buttonCancel: 'Cancel',
        buttonYes: 'Remove',
      },
      sameNameFound: {
        typeMessage: 'sameNameFound',
        show: true,
        title: 'Attention',
        message:
          'This name has already been used! Try to come up with another name for your mix.',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      emptyName: {
        typeMessage: 'emptyName',
        show: true,
        title: 'Attention',
        message: 'The name cannot be empty.',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      sameMixFound: {
        typeMessage: 'sameMixFound',
        show: true,
        title: 'Attention',
        message1: 'Such a mix already exists in the list of my mixes called:',
        message: '',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      exitApp: {
        typeMessage: 'exitApp',
        show: true,
        title: 'Attention',
        message: 'Do you really want to exit the app?',
        buttonCancel: 'No',
        buttonYes: 'Yes',
      },
      OpenDescription: {
        typeMessage: 'OpenDescription',
        show: true,
        title: 'Description of the rhythm',
        message: '',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      downloadFromCloud: {
        typeMessage: 'downloadFromCloud',
        show: true,
        title: 'Downloading a file',
        message: '',
        message1: 'Do you really want to download the',
        message2:
          'file to your device to be able to listen to it without an internet connection?',
        size: 'File Size:',
        storage: '',
        name: '',
        category: '',
        id: '',
        buttonCancel: 'No',
        buttonYes: 'Yes',
      },
      endDownload: {
        typeMessage: 'endDownload',
        show: true,
        title: 'Loading',
        message: 'Download completed successfully!',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      deleteFromDevice: {
        typeMessage: 'deleteFromDevice',
        show: true,
        title: 'Deleting a file',
        message: '',
        message1: 'Do you really want to delete the',
        message2:
          'file from your device? You will still be able to listen to this file over the Internet.',
        sound: '',
        id: '',
        name: '',
        size: 'File Size:',
        category: '',
        buttonCancel: 'No',
        buttonYes: 'Yes',
      },
      deleteAllFromDevice: {
        typeMessage: 'deleteAllFromDevice',
        show: true,
        title: 'Deleting all downloaded files',
        message:
          'Do you really want to delete all downloaded sounds from your device? You will have the opportunity to listen via the Internet or download the necessary sounds to your phone again.',
        buttonCancel: 'No',
        buttonYes: 'Yes',
      },
      endDelete: {
        typeMessage: 'endDownload',
        show: true,
        title: 'Deleting',
        message: 'The file has been deleted!',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      endDeleteAll: {
        typeMessage: 'endDeleteAll',
        show: true,
        title: 'Deleting all downloaded sounds',
        message: '',
        message2: 'All downloaded sounds have been deleted! Total - ',
        message3: '. Total volume: ',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      noFilesToDelete: {
        typeMessage: 'noFilesToDelete',
        show: true,
        title: 'Deleting all downloaded sounds',
        message: 'No files to delete!',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      TotalSize: {
        typeMessage: 'TotalSize',
        show: true,
        title: 'Size of downloaded files',
        message: '',
        message1: 'Total in the "Sounds" catalog:     ',
        message2: 'Total in the "Music" catalog:   ',
        message3: 'Total in the "Brain Waves" catalog:     ',
        message4: 'Total in all catalogs:     ',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      feedbackSuccess: {
        typeMessage: 'feedbackSuccess',
        show: true,
        title: 'The request was accepted',
        message: '',
        buttonCancel: '',
        buttonYes: 'OK',
      },
      maxSounds: {
        typeMessage: 'maxSounds',
        show: true,
        title: 'Превышен лимит',
        message: `You can add no more than ${CONST.maxSounds} sounds!`,
        buttonCancel: '',
        buttonYes: 'ОК',
      },
      error: {
        typeMessage: 'error',
        show: true,
        title: 'Error!',
        message: '',
        buttonCancel: '',
        buttonYes: 'OK',
      },
    },
    feedback: {
      firstName: 'Your name',
      emailLabel: 'Email',
      topicLabel: 'Topic',
      descriptionLabel: 'Description of your request',
      button: 'Send',
      errors: {
        intervalSending: 'Sending the next request will be possible in ',
        incorrectEmail: 'Incorrect email has been entered!',
        emptyName: 'Enter your name',
        emptyTopic: 'Enter the subject of the request',
        emptyDescription: 'Describe your require',
        maxLengthName: `The name must not exceed ${CONST.feedback.maxLengthFirstName} characters`,
        maxLengthTopic: `The topic name should not exceed ${CONST.feedback.maxLengthTopic} characters`,
        maxLengthDescription: `The description of the require should not exceed ${CONST.feedback.maxLengthDescription} characters`,
        minLengthTopic: `The name of the topic should not be less than ${CONST.feedback.minLengthTopic} characters`,
        minLengthDescription: `The description of the require should not be less than ${CONST.feedback.minLengthDescription} characters`,
      },
      resultSuccess: 'The require was accepted under the MS ',
      resultError: 'Error sending a request ',
    },
  },
};
