export const THEME = {
  theme: {
    _key: 'Theme',
  },
  currentTheme: 'MAIN_THEME',
  MAIN_THEME: {
    BACKGROUNDCOLOR_LG: ['#3b555d', '#233237', '#204d48', '#233237', '#3b555d'],
    BACKGROUNDCOLOR_LG_Disabled: ['#104E8B', '#4A708B', '#104E8B'],
    BACKGROUNDCOLOR: '#233237',
    BACKGROUNDCOLOR_HEADER: '#3b555d',
    BACKGROUNDCOLOR_TILES: '#3b555d',
    NO_ACTIVE: '#146185',
    TEXT_COLOR: 'white',
    ITEM_COLOR: 'white',
    CHECK_COLOR: '#15a522',
    DANGER_COLOR: '#d81b60',
    name: 'MAIN_THEME',
    booked: 'rgba(192, 159, 106, 1)',
    borderColor: 'yellow',
    borderColor2: '#414141',
    borderColorRGBA: 'rgba(255, 255, 0, 0.3)',
    borderColorRGBA2: 'rgba(21, 165, 34, 0.3)',
  },
  LIGHT_THEME: {
    BACKGROUNDCOLOR_LG: ['#efefef', '#cccccc', '#efefef'],
    BACKGROUNDCOLOR_LG_Disabled: ['#efefef', '#cccccc', '#efefef'],
    BACKGROUNDCOLOR: '#cccccc',
    BACKGROUNDCOLOR_HEADER: '#efefef',
    BACKGROUNDCOLOR_TILES: '#efefef',
    NO_ACTIVE: '#cccccc',
    TEXT_COLOR: 'black',
    ITEM_COLOR: 'black',
    CHECK_COLOR: '#15a522',
    DANGER_COLOR: '#d81b60',
    name: 'LIGHT_THEME',
    booked: 'rgba(192, 159, 106, 1)',
    borderColor: '#15a522',
    borderColor2: '#414141',
    borderColorRGBA2: 'rgba(255, 255, 0, 0.3)',
    borderColorRGBA: 'rgba(21, 165, 34, 0.3)',
  },
  MAIN_BACKGROUNDSTYLES: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  TITLE_FONT: {fontSize: 20, fontWeight: 'bold', fontFamily: 'OpenSans-Bold'},
  TITLE_FONT2: {fontSize: 16, fontWeight: 'bold', fontFamily: 'OpenSans-Bold'},
  TITLE_FONT3: {fontSize: 14, fontFamily: 'OpenSans-Regular'},
  TITLE_FONT4: {fontSize: 30, fontWeight: 'bold', fontFamily: 'OpenSans-Bold'},
  TEXT_FONT: {fontSize: 16, fontFamily: 'OpenSans-Regular'},
  TEXT_FONT2: {fontSize: 14, fontWeight: 'bold', fontFamily: 'OpenSans-Bold'},
  TEXT_FONT3: {fontSize: 12, fontFamily: 'OpenSans-Regular'},
  TEXT_FONT4: {fontSize: 14, fontFamily: 'OpenSans-Regular'},
  TEXT_FONT5: {fontSize: 30, fontFamily: 'OpenSans-Regular'},
  SHADOW_FOR_IOS: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
  },
};
